// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udG5od3hnY3Zxb2R0ZXhrd3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxODg4MjYsImV4cCI6MjA4MDc2NDgyNn0.8v5fOEkjhHks2xZX5kAe28zlzPGa7XiDe_DGEkExUG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
